# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#landing"
  weight = 10

[[main]]
  name = "Recent Publications"
  url = "#featured"
  weight = 20

[[main]]
  name = "Projects"
  url = "#projects"
  weight = 30

[[main]]
  name = "Contact Me"
  url = "#contact"
  weight = 40

[[main]]
  name = "Know More"
  url = ""
  hasChildren = true
  weight = 50

[[main]]
  parent = "Know More"
  name = "About Me"
  url = "about/"
  weight = 1

[[main]]
  parent = "Know More"
  name = "My Publications"
  url = "publication/"
  weight = 2

[[main]]
  parent = "Know More"
  name = "My Talks"
  url = "talk/"
  weight = 3

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
[[main]]
  parent = "Know More"
  name = "Full CV"
  url = "static/files/em_prestige_cv.pdf/"
  weight = 4

#[[main]]
#  name = "Publications"
#  url = "#featured"
#  hasChildren = true
#  weight = 20

#[[main]]
#  parent = "Publications"
#  name = "Featured Publications"
#  url = "#featured"

#[[main]]
#  parent = "Publications"
#  name = "All Publications"
#  url = "publication/"
