# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

#[[main]]
#  name = "Publications"
#  url = "publications/"
#  weight = 30

[[main]]
  name = "Projects"
  url = "#projects"
  weight = 40

[[main]]
  name = "Talks"
  url = "#talks"
  weight = 50

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 60

[[main]]
  name = "Publications"
  url = "#"
  hasChildren = true
  weight = 30

[[main]]
  parent = "Publications"
  name = "Featured Publications"
  url = "#featured"

[[main]]
  parent = "Publications"
  name = "Recent Publications"
  url = "publications/"

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
